[
    {
      constant: !0,
      inputs: [],
      name: 'name',
      outputs: [{ name: '', type: 'string' }],
      payable: !1,
      stateMutability: 'view',
      type: 'function',
    },
    {
      constant: !1,
      inputs: [
        { name: '_spender', type: 'address' },
        { name: '_value', type: 'uint256' },
      ],
      name: 'approve',
      outputs: [{ name: '_success', type: 'bool' }],
      payable: !1,
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      constant: !0,
      inputs: [],
      name: 'totalSupply',
      outputs: [{ name: '', type: 'uint256' }],
      payable: !1,
      stateMutability: 'view',
      type: 'function',
    },
    {
      constant: !1,
      inputs: [{ name: '_dailyPotionLimit', type: 'uint256' }],
      name: 'setDailyPotionLimit',
      outputs: [],
      payable: !1,
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      constant: !1,
      inputs: [
        { name: '_amount', type: 'uint256' },
        { name: '_createdAt', type: 'uint256' },
        { name: '_signature', type: 'bytes' },
        { name: '_spender', type: 'address' },
        { name: '_approvedAmount', type: 'uint256' },
        { name: '_data', type: 'bytes' },
      ],
      name: 'checkpointAndCall',
      outputs: [{ name: '_balance', type: 'uint256' }],
      payable: !0,
      stateMutability: 'payable',
      type: 'function',
    },
    {
      constant: !1,
      inputs: [
        { name: '_from', type: 'address' },
        { name: '_to', type: 'address' },
        { name: '_value', type: 'uint256' },
      ],
      name: 'transferFrom',
      outputs: [{ name: '_success', type: 'bool' }],
      payable: !1,
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      constant: !0,
      inputs: [],
      name: 'decimals',
      outputs: [{ name: '', type: 'uint8' }],
      payable: !1,
      stateMutability: 'view',
      type: 'function',
    },
    {
      constant: !0,
      inputs: [{ name: '', type: 'address' }],
      name: 'minter',
      outputs: [{ name: '', type: 'bool' }],
      payable: !1,
      stateMutability: 'view',
      type: 'function',
    },
    {
      constant: !0,
      inputs: [{ name: '_owner', type: 'address' }],
      name: 'getCheckpoint',
      outputs: [
        { name: '_amount', type: 'uint256' },
        { name: '_createdAt', type: 'uint256' },
      ],
      payable: !1,
      stateMutability: 'view',
      type: 'function',
    },
    {
      constant: !1,
      inputs: [],
      name: 'unpause',
      outputs: [],
      payable: !1,
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      constant: !1,
      inputs: [
        { name: '_to', type: 'address' },
        { name: '_value', type: 'uint256' },
      ],
      name: 'mint',
      outputs: [{ name: '_success', type: 'bool' }],
      payable: !1,
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      constant: !1,
      inputs: [{ name: '_value', type: 'uint256' }],
      name: 'burn',
      outputs: [{ name: '_success', type: 'bool' }],
      payable: !1,
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      constant: !0,
      inputs: [],
      name: 'paused',
      outputs: [{ name: '', type: 'bool' }],
      payable: !1,
      stateMutability: 'view',
      type: 'function',
    },
    {
      constant: !1,
      inputs: [{ name: '_removedMinters', type: 'address[]' }],
      name: 'removeMinters',
      outputs: [],
      payable: !1,
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      constant: !0,
      inputs: [],
      name: 'cappedSupply',
      outputs: [{ name: '', type: 'uint256' }],
      payable: !1,
      stateMutability: 'view',
      type: 'function',
    },
    {
      constant: !0,
      inputs: [{ name: '', type: 'address' }],
      name: 'balanceOf',
      outputs: [{ name: '', type: 'uint256' }],
      payable: !1,
      stateMutability: 'view',
      type: 'function',
    },
    {
      constant: !1,
      inputs: [{ name: '_addedMinters', type: 'address[]' }],
      name: 'addMinters',
      outputs: [],
      payable: !1,
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      constant: !1,
      inputs: [
        { name: '_from', type: 'address' },
        { name: '_value', type: 'uint256' },
      ],
      name: 'burnFrom',
      outputs: [{ name: '_success', type: 'bool' }],
      payable: !1,
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      constant: !1,
      inputs: [],
      name: 'pause',
      outputs: [],
      payable: !1,
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      constant: !0,
      inputs: [{ name: '', type: 'uint256' }],
      name: 'minters',
      outputs: [{ name: '', type: 'address' }],
      payable: !1,
      stateMutability: 'view',
      type: 'function',
    },
    {
      constant: !0,
      inputs: [],
      name: 'dailyPotionLimit',
      outputs: [{ name: '', type: 'uint256' }],
      payable: !1,
      stateMutability: 'view',
      type: 'function',
    },
    {
      constant: !1,
      inputs: [{ name: '_newAdmin', type: 'address' }],
      name: 'changeAdmin',
      outputs: [],
      payable: !1,
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      constant: !0,
      inputs: [],
      name: 'symbol',
      outputs: [{ name: '', type: 'string' }],
      payable: !1,
      stateMutability: 'view',
      type: 'function',
    },
    {
      constant: !1,
      inputs: [],
      name: 'removeAdmin',
      outputs: [],
      payable: !1,
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      constant: !1,
      inputs: [
        { name: '_to', type: 'address' },
        { name: '_value', type: 'uint256' },
      ],
      name: 'transfer',
      outputs: [{ name: '_success', type: 'bool' }],
      payable: !1,
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      constant: !0,
      inputs: [{ name: '_addr', type: 'address' }],
      name: 'isMinter',
      outputs: [{ name: '', type: 'bool' }],
      payable: !1,
      stateMutability: 'view',
      type: 'function',
    },
    {
      constant: !1,
      inputs: [
        { name: '_spender', type: 'address' },
        { name: '_value', type: 'uint256' },
        { name: '_data', type: 'bytes' },
      ],
      name: 'approveAndCall',
      outputs: [{ name: '_success', type: 'bool' }],
      payable: !1,
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      constant: !1,
      inputs: [
        { name: '_owner', type: 'address' },
        { name: '_amount', type: 'uint256' },
        { name: '_createdAt', type: 'uint256' },
        { name: '_signature', type: 'bytes' },
      ],
      name: 'checkpoint',
      outputs: [{ name: '_balance', type: 'uint256' }],
      payable: !1,
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      constant: !0,
      inputs: [
        { name: '', type: 'address' },
        { name: '', type: 'address' },
      ],
      name: 'allowance',
      outputs: [{ name: '', type: 'uint256' }],
      payable: !1,
      stateMutability: 'view',
      type: 'function',
    },
    {
      constant: !1,
      inputs: [
        { name: '_spender', type: 'address' },
        { name: '_value', type: 'uint256' },
        { name: '_data', type: 'bytes' },
      ],
      name: 'approveAndCallPayable',
      outputs: [{ name: '_success', type: 'bool' }],
      payable: !0,
      stateMutability: 'payable',
      type: 'function',
    },
    {
      constant: !0,
      inputs: [],
      name: 'admin',
      outputs: [{ name: '', type: 'address' }],
      payable: !1,
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { name: '_name', type: 'string' },
        { name: '_symbol', type: 'string' },
        { name: '_dailyPotionLimit', type: 'uint256' },
      ],
      payable: !1,
      stateMutability: 'nonpayable',
      type: 'constructor',
    },
    {
      anonymous: !1,
      inputs: [
        { indexed: !0, name: '_owner', type: 'address' },
        { indexed: !0, name: '_amount', type: 'uint256' },
      ],
      name: 'BreedingPotionCheckpoint',
      type: 'event',
    },
    {
      anonymous: !1,
      inputs: [
        { indexed: !0, name: '_from', type: 'address' },
        { indexed: !0, name: '_to', type: 'address' },
        { indexed: !1, name: '_value', type: 'uint256' },
      ],
      name: 'Transfer',
      type: 'event',
    },
    {
      anonymous: !1,
      inputs: [
        { indexed: !0, name: '_owner', type: 'address' },
        { indexed: !0, name: '_spender', type: 'address' },
        { indexed: !1, name: '_value', type: 'uint256' },
      ],
      name: 'Approval',
      type: 'event',
    },
    {
      anonymous: !1,
      inputs: [{ indexed: !0, name: '_minter', type: 'address' }],
      name: 'MinterAdded',
      type: 'event',
    },
    {
      anonymous: !1,
      inputs: [{ indexed: !0, name: '_minter', type: 'address' }],
      name: 'MinterRemoved',
      type: 'event',
    },
    { anonymous: !1, inputs: [], name: 'Paused', type: 'event' },
    { anonymous: !1, inputs: [], name: 'Unpaused', type: 'event' },
    {
      anonymous: !1,
      inputs: [
        { indexed: !0, name: '_oldAdmin', type: 'address' },
        { indexed: !0, name: '_newAdmin', type: 'address' },
      ],
      name: 'AdminChanged',
      type: 'event',
    },
    {
      anonymous: !1,
      inputs: [{ indexed: !0, name: '_oldAdmin', type: 'address' }],
      name: 'AdminRemoved',
      type: 'event',
    },
  ]